// <auto-generated />
namespace laIdealShipping.Web.DataContexts.laIdealShippingMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddingContactInfoAttributes2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingContactInfoAttributes2));
        
        string IMigrationMetadata.Id
        {
            get { return "201409291422450_AddingContactInfoAttributes2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
